
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yess
 */
public class Frame1 extends javax.swing.JFrame {
    String temp  = "";
    Double ti,bt,hi;
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        bb = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        per = new javax.swing.JRadioButton();
        lak = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        kideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PENGHITUNGAN BERAT BADAN IDEAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 60, 310, 20);

        jLabel2.setText("Jenis Kelamin");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 220, 100, 20);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 100, 41, 20);

        jLabel4.setText("Tinggi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 140, 45, 20);

        jLabel5.setText("Berat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 180, 36, 20);
        getContentPane().add(nama);
        nama.setBounds(200, 100, 290, 26);

        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        getContentPane().add(bb);
        bb.setBounds(200, 180, 50, 26);

        tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiActionPerformed(evt);
            }
        });
        getContentPane().add(tinggi);
        tinggi.setBounds(200, 140, 50, 26);

        buttonGroup5.add(per);
        per.setText("Perempuan");
        per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perActionPerformed(evt);
            }
        });
        getContentPane().add(per);
        per.setBounds(200, 220, 113, 29);

        buttonGroup5.add(lak);
        lak.setText("Laki-Laki");
        lak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakActionPerformed(evt);
            }
        });
        getContentPane().add(lak);
        lak.setBounds(340, 220, 95, 29);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 290, 77, 29);

        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 290, 79, 29);

        jButton3.setText("Coba Lagi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 290, 120, 29);

        jLabel6.setText("Berat Badan Ideal anda adalah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 350, 230, 20);
        getContentPane().add(kideal);
        kideal.setBounds(360, 350, 60, 26);

        jLabel7.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 400, 200, 20);
        getContentPane().add(hasil);
        hasil.setBounds(140, 430, 530, 26);
        getContentPane().add(saran);
        saran.setBounds(140, 470, 530, 26);

        jLabel8.setText("cm");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 140, 21, 20);

        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 180, 17, 20);

        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 350, 17, 20);

        setBounds(0, 0, 859, 634);
    }// </editor-fold>//GEN-END:initComponents

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbActionPerformed

    private void tinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if (bb.getText().equals("") || tinggi.getText().equals("")
             || nama.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Kotak Isian belum diisi");
    }else if (per.isSelected() || lak.isSelected()) {
        try{
            Proses();
        }
        catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Inputan ada yang salah");
        }            
        } else {
               JOptionPane.showMessageDialog(null, "Jenis Kelamin belum dipilih" );
    }
    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perActionPerformed
    per.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_perActionPerformed

    private void lakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakActionPerformed
    lak.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_lakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        buttonGroup5.clearSelection();    
        per.setSelected(false);
        lak.setSelected(false);
        nama.setText("");
        tinggi.setText("");
        bb.setText("");
        kideal.setText("");
        hasil.setText("");
        saran.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bb;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kideal;
    private javax.swing.JRadioButton lak;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton per;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() { //To change body of generated methods, choose Tools | Templates.
        ti = Double.valueOf(tinggi.getText());
        bt = Double.valueOf(bb.getText());
        
        if (per.isSelected()){
        hi = (ti - 100) * 1;
        } else if (lak.isSelected()){
        hi = (ti - 104) * 1;
        }
        temp = Double.toString(hi.intValue());
        
        if(hi < bt){
            kideal.setText(temp);
            hasil.setText("Maaf" + nama.getText() + " , Sepertinya anda overweight :(");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
        } else if (hi > bt){
         kideal.setText(temp);
            hasil.setText("Maaf" + nama.getText() + " , Sepertinya anda underweight :(");
            saran.setText("Makanlah makanan berkarbohidrat");
        } else {
         kideal.setText(temp);
            hasil.setText("Maaf" + nama.getText() + " , Berat badan sudah ideal :)");
            saran.setText("Lanjutkan pola makan dan gaya hidup sehat");
        }
    }
}
